# Generated by Django 5.0.2 on 2024-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('comment_msg', models.CharField(max_length=1000)),
                ('comment_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
